first commit in vector
T-y-c-o-o-n/first-term pull request #1
Opened 2020-07-04 22:19 UTC by T-y-c-o-o-n

my first pull-request as far as I understand

2020-07-05 16:28 UTC, kt-cpp requested changes

2020-07-05 16:28 UTC, kt-cpp commented on vector/vector.h
> +#include <vector>
[minor] Вектор внутри самописного?

2020-07-05 16:28 UTC, kt-cpp commented on vector/vector.h
> +	typedef T const *const_iterator;
[note] `using` более современно и читаемо

2020-07-05 16:28 UTC, kt-cpp commented on vector/vector.h
> +	size_t _capacity;
[minor] Лучше не называть с `_` пользовательские переменные. Если хочется, то лучше ставить в конце. Начало это прирогатива стандартной библиотеки

2020-07-05 16:28 UTC, kt-cpp commented on vector/vector.h
> +			for (auto it = other.begin(); it != other.end(); ++it) {
[note] `for (const T &e : other)`

2020-07-05 16:28 UTC, kt-cpp commented on vector/vector.h
> +	vector &operator=(vector rhs)
[minor] Если не принимать по значению, то можно избежать лишнего копирования в ситуации `a = a;`

2020-07-05 16:28 UTC, kt-cpp commented on vector/vector.h
> +		destroy(end() - 1, end());
[note] Формально правильно, но всё же странно. Проще просто вызвать деструктор у последнего элемента, мб даже быстрее т.к. компилятор не будет компилить `for`

2020-07-05 16:28 UTC, kt-cpp commented on vector/vector.h
> +			vector<T> temp(*this);
[minor] `<T>` тут не обязателен

2020-07-05 16:28 UTC, kt-cpp commented on vector/vector.h
> +		}
[minor] Этот случай нет смысла рассматривать отдельно

2020-07-05 16:28 UTC, kt-cpp commented on vector/vector.h
> +		push_back(val);
Если у тебя будет вектор векторов ты проиграешь по времени из-за копирований, плюс зачем-то копируешь значение несколько раз, когда можно 1:
* В параметре функции
* При вызове операторе присваивания, который тут кстати тоже не нужен
Плюс разбор пустого и непустого вектора тут тоже не нужен, в исправленной реализации ты поймёшь

2020-07-05 16:28 UTC, kt-cpp commented on vector/vector.h
> +		return _data;
insert должен возвращать итератор на вставленный элемент, а не начало данных

2020-07-05 16:28 UTC, kt-cpp commented on vector/vector.h
> +		size_t delta = finish - start;
Для разницы указателей, коими у тебя являются итераторы, используется другой тип

2020-07-05 16:28 UTC, kt-cpp commented on vector/vector.h
> +		if (delta <= 0) return start;
![image](https://user-images.githubusercontent.com/67123994/86537024-d7339100-bef4-11ea-920b-d86e5920ffc1.png)

2020-07-05 16:28 UTC, kt-cpp commented on vector/vector.h
> +		for (auto it = const_cast<iterator>(start); it < end() - delta; ++it) {
Почему этот каст валиден?

2020-07-05 16:28 UTC, kt-cpp commented on vector/vector.h
> +			*it = *(it + delta);
Снова копирования в присваиваниях, когда без них можно обойтись

2020-07-05 16:28 UTC, kt-cpp commented on vector/vector.h
> +		}
[minor] Почему скобки разные от общего стиля?

2020-07-05 16:28 UTC, kt-cpp commented on vector/vector.h
> +		}
Порядок деструкций должен быть обратным порядком конструирования

2020-07-05 16:28 UTC, kt-cpp commented on vector/vector.h
> +	}
Лишняя копия, когда её можно не делать в аргументе

2020-07-05 16:28 UTC, kt-cpp commented on vector/vector.h
> +		destroy(end() - 1, end());
[minor] Почему не переиспользовал `destroy` от одного аргумента?

2020-07-05 21:16 UTC, T-y-c-o-o-n commented on vector/vector.h
> +		}
скобки не разные, в циклах открывающая на той же строке, а в функциях на другой

2020-07-05 21:41 UTC, T-y-c-o-o-n commented on vector/vector.h
> +		}
Тут, скорее всего, неизвестен порядок конструкторов элементов (например, могли элементы добавляться в начало каждый раз)

2020-07-07 17:30 UTC, kt-cpp requested changes

2020-07-07 17:30 UTC, kt-cpp commented on vector/vector.h
> +		if (res == end() - 1 || last == end() + delta) return end();
что это и зачем

2020-07-07 17:30 UTC, kt-cpp commented on vector/vector.h
> +	iterator erase(iterator first, iterator last)
ты сделал перегрузки для iterator, нужно для const_iterator

2020-07-07 18:43 UTC, T-y-c-o-o-n commented on vector/vector.h
> +		if (res == end() - 1 || last == end() + delta) return end();
я так понял постусловие возвращаемого значения в erase:
if (res == end() - 1) это проверка второй ситуации (if pos refers to the last element),
а if (last == end() + delta) это проверка третьей ситуации (if last == end() prior to removal)

2020-07-09 22:18 UTC, kt-cpp commented on vector/vector.h
> +		for (auto it = const_cast<iterator>(start); it < end() - delta; ++it) {
Не вижу ответа

2020-07-09 22:25 UTC, kt-cpp commented on vector/vector.h
> +		}
Ужасно, приведи к одному виду

2020-07-09 22:29 UTC, kt-cpp commented on vector/vector.h
> +		if (res == end() - 1 || last == end() + delta) return end();
В правильно написанои коде этот разбор случвев не нужен

2020-07-09 22:58 UTC, kt-cpp commented on vector/vector.h
> +		}
Красиво 😎

2020-07-09 22:58 UTC, kt-cpp commented on vector/vector.h
> +		for (auto it = const_cast<iterator>(start); it < end() - delta; ++it) {
Ладно убрал их

2020-07-09 23:00 UTC, kt-cpp requested changes
Слегка экономишь на скобках и не везде консистетно форматироание фигурных скобор

2020-09-20 13:15 UTC, kt-cpp approved these changes

2020-09-20 13:15 UTC, merged