optimal commit
T-y-c-o-o-n/first-term pull request #4
Opened 2020-07-10 14:42 UTC by T-y-c-o-o-n

Leave a comment

2020-07-10 16:40 UTC, kt-cpp requested changes

2020-07-10 16:40 UTC, kt-cpp commented on bigint-optimized/shared_data.h
> +using digit_t = uint32_t;
[minor] Зачем это публично да и зачем вообще?

2020-07-10 16:40 UTC, kt-cpp commented on bigint-optimized/shared_data.h
> +	~shared_data();
[minor] `= default`?

2020-07-10 16:40 UTC, kt-cpp commented on bigint-optimized/shared_data.h
> +	std::vector<digit_t> const &get_buffer() const;
[minor] Можно было и публичным сделать, всё равно деталь реализации этот класс

2020-07-10 16:40 UTC, kt-cpp commented on bigint-optimized/shared_data.cpp
> +	buffer = std::vector<digit_t>(size, digit);
[minor] Инициализация членов класса

2020-07-10 16:40 UTC, kt-cpp commented on bigint-optimized/shared_data.cpp
> +	buffer = std::vector<digit_t>(digits);
[minor] Инициализация членов класса

2020-07-10 16:40 UTC, kt-cpp commented on bigint-optimized/shared_data.cpp
> +	this -> dec();
[minor] Просто `dec()` без `this`

2020-07-10 16:40 UTC, kt-cpp commented on bigint-optimized/shared_data.cpp
> +	if (ref_cnt == 1) return this;
[minor] Опять экономия на фигурных скобках

2020-07-10 16:40 UTC, kt-cpp commented on bigint-optimized/optimal_storage.h
> +	static size_t const MAX_STATIC_DATA_SIZE = sizeof(shared_data) / sizeof(uint32_t);
[minor] `constexpr`. А ещё ты хранишь указатель, а не `shared_data`. Так что выражение не имеет смысла. А ещё тут забыли `digit_t`, хотя его просто надо выпилить

2020-07-10 16:40 UTC, kt-cpp commented on bigint-optimized/optimal_storage.cpp
> +		}
[minor] `std::fill`

2020-07-10 16:40 UTC, kt-cpp commented on bigint-optimized/optimal_storage.cpp
> +//		std::copy(static_data, other.static_data, size());
[minor] Зачем-то закомменчен почти правильный коды. Может ты хотел `std::copy_n`

2020-07-10 16:40 UTC, kt-cpp commented on bigint-optimized/optimal_storage.cpp
> +		dynamic_data -> inc();
[minor] Пробелы лишние вокруг. Пишу одни раз

2020-07-10 16:40 UTC, kt-cpp commented on bigint-optimized/shared_data.cpp
> +	if (ref_cnt == 1) return this;
Таких много пишу один раз

2020-07-10 16:40 UTC, kt-cpp commented on bigint-optimized/optimal_storage.cpp
> +//		std::copy(static_data, other.static_data, size());
Такое есть несколько раз

2020-07-10 16:40 UTC, kt-cpp commented on bigint-optimized/optimal_storage.cpp
> +	}
[minor] Такой код встречается несколько раз. Вынеси

2020-07-10 16:40 UTC, kt-cpp commented on bigint-optimized/optimal_storage.cpp
> +	}
Очень странный контракт. Либо ты умеешь делать ресайз на меньший размер, либо ставишь ассёрт. Это не то, что я и кто-то ещё ждёт от ресайза

2020-07-10 16:40 UTC, kt-cpp commented on bigint-optimized/optimal_storage.cpp
> +}
Лучше через эту функцию реализовать ресайз выше перевызвав данную с digit равным 0, или сделать такой дефолтный параметр вообще. Т.е. тело функции выше должно оказаться здесь

2020-07-10 16:40 UTC, kt-cpp commented on bigint-optimized/optimal_storage.cpp
> +	if (small()) return reinterpret_cast<const_iterator>(&static_data);
[minor] Каст тут не нужен. Навешивать конст нормально неявно. Мне кажется вообще можно просто `return static_data`

2020-07-10 16:40 UTC, kt-cpp commented on bigint-optimized/optimal_storage.cpp
> +	}
А тут сломан контракт, потому что я ожидаю, что в случае увеличения размера будет заполнена нулям

2020-07-10 16:40 UTC, kt-cpp commented on bigint-optimized/optimal_storage.cpp
> +	if (small()) return reinterpret_cast<const_iterator>(&static_data);
Ниже есть такой же

2020-07-10 16:40 UTC, kt-cpp commented on bigint-optimized/optimal_storage.cpp
> +	return dynamic_data -> data();
Теперь я могу изменять шаренные данные через этот итератор

2020-07-10 16:42 UTC, T-y-c-o-o-n commented on bigint-optimized/optimal_storage.cpp
> +//		std::copy(static_data, other.static_data, size());
да, хотел, просто не понял вначале, как его использовать

2020-07-10 17:28 UTC, kt-cpp commented on bigint-optimized/optimal_storage.h
> +	static size_t const MAX_STATIC_DATA_SIZE = sizeof(shared_data) / sizeof(uint32_t);
Там не `void *` у тебя, но всё же уже лучше

2020-07-10 17:28 UTC, kt-cpp commented on bigint-optimized/optimal_storage.cpp
> +		}
Не исправил

2020-07-10 17:30 UTC, kt-cpp commented on bigint-optimized/optimal_storage.cpp
> +	return dynamic_data -> data();
ыыы просто убрал перегрузки

2020-07-10 17:35 UTC, kt-cpp commented on bigint-optimized/optimal_storage.cpp
> +	assert (new_sz > size_);
[minor] Наверное можно и не строгий знак..

2020-07-10 17:35 UTC, kt-cpp commented on bigint-optimized/optimal_storage.cpp
> +		}
[minor] `std::fill`

2020-07-10 17:35 UTC, kt-cpp commented on bigint-optimized/optimal_storage.cpp
> +		}
А ещё тут не нули должны быть, а `digit`, так что не минор

2020-07-10 17:35 UTC, kt-cpp commented on bigint-optimized/optimal_storage.cpp
> +	size_t size_was = size_;
[minor] Всё что связано с этой переменной не нужно потому что прочитай доку по resize https://en.cppreference.com/w/cpp/container/vector/resize

2020-07-10 17:36 UTC, T-y-c-o-o-n commented on bigint-optimized/optimal_storage.cpp
> +		}
minor bug в следующем коммите как раз был к этому...

2020-07-10 17:49 UTC, kt-cpp requested changes

2020-07-10 17:49 UTC, kt-cpp commented on bigint-optimized/optimal_storage.cpp
> +//		}
[minor] Комменты в проде..

2020-07-10 17:49 UTC, kt-cpp commented on bigint-optimized/optimal_storage.cpp
> +		std::fill(static_data + size_, static_data + new_sz, digit);
[minor] Комменты в проде..

2020-08-15 11:10 UTC, T-y-c-o-o-n commented on bigint-optimized/optimal_storage.cpp
> +	size_t size_was = size_;
Исправил. Она действительно лишняя

2020-09-20 22:56 UTC, kt-cpp requested changes

2020-09-20 22:56 UTC, kt-cpp commented on bigint-optimized/optimal_storage.cpp
> +			is_small = false;
[minor] Чтобы избежать лишних копирований можно прям в классе `shared_data` сделать конструктор от двух итераторов или указателей. Тогда не придётся копировать вектор

2020-10-14 21:49 UTC, kt-cpp approved these changes

2020-10-14 21:49 UTC, merged